/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

/**
 *
 * @author Holi
 */
public class vistaPerfil extends javax.swing.JPanel {

    /** Creates new form vistaPerfil */
    public vistaPerfil() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEditarPerfil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel71 = new javax.swing.JPanel();
        jPanel72 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jRadioButton126 = new javax.swing.JRadioButton();
        jRadioButton127 = new javax.swing.JRadioButton();
        jRadioButton128 = new javax.swing.JRadioButton();
        jRadioButton129 = new javax.swing.JRadioButton();
        jRadioButton130 = new javax.swing.JRadioButton();
        btnModificarViaje = new javax.swing.JButton();
        jPanel75 = new javax.swing.JPanel();
        jPanel76 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel77 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jPanel78 = new javax.swing.JPanel();
        jPanel79 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jPanel80 = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jPanel81 = new javax.swing.JPanel();
        jPanel82 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jPanel83 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jPanel84 = new javax.swing.JPanel();
        jPanel85 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel86 = new javax.swing.JPanel();
        jPanel87 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jRadioButton131 = new javax.swing.JRadioButton();
        jRadioButton132 = new javax.swing.JRadioButton();
        jRadioButton133 = new javax.swing.JRadioButton();
        jRadioButton134 = new javax.swing.JRadioButton();
        jRadioButton135 = new javax.swing.JRadioButton();
        jButton18 = new javax.swing.JButton();
        jPanel88 = new javax.swing.JPanel();
        jPanel89 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jPanel90 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jPanel91 = new javax.swing.JPanel();
        jPanel92 = new javax.swing.JPanel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jPanel93 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jPanel94 = new javax.swing.JPanel();
        jPanel95 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jPanel96 = new javax.swing.JPanel();
        jPanel97 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jRadioButton136 = new javax.swing.JRadioButton();
        jRadioButton137 = new javax.swing.JRadioButton();
        jRadioButton138 = new javax.swing.JRadioButton();
        jRadioButton139 = new javax.swing.JRadioButton();
        jRadioButton140 = new javax.swing.JRadioButton();
        jButton21 = new javax.swing.JButton();
        jPanel98 = new javax.swing.JPanel();
        jPanel99 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jPanel100 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Cat_Profile_100px.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nombre completo");

        jLabel3.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("@usuario");

        btnEditarPerfil.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnEditarPerfil.setForeground(new java.awt.Color(102, 102, 102));
        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Settings_40px.png"))); // NOI18N
        btnEditarPerfil.setText("Editar perfil");
        btnEditarPerfil.setBorderPainted(false);
        btnEditarPerfil.setContentAreaFilled(false);
        btnEditarPerfil.setDefaultCapable(false);
        btnEditarPerfil.setFocusPainted(false);
        btnEditarPerfil.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Settings_35px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(btnEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditarPerfil)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel71.setBackground(new java.awt.Color(156, 255, 87));
        jPanel71.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel71.setLayout(null);

        jPanel72.setBackground(new java.awt.Color(156, 255, 87));
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(156, 255, 87));
        jLabel34.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Titulo del viaje");
        jPanel72.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, 230, 20));

        jLabel35.setBackground(new java.awt.Color(156, 255, 87));
        jLabel35.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Destino");
        jPanel72.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 24));

        jPanel71.add(jPanel72);
        jPanel72.setBounds(0, 160, 250, 50);

        jPanel73.setBackground(new java.awt.Color(156, 255, 87));
        jPanel73.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel73.setLayout(null);

        jPanel74.setBackground(new java.awt.Color(156, 255, 87));

        jLabel58.setBackground(new java.awt.Color(156, 255, 87));
        jLabel58.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel58.setText("Santiago, Chile.");

        jRadioButton126.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton126.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton126.setContentAreaFilled(false);
        jRadioButton126.setFocusPainted(false);
        jRadioButton126.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton126ActionPerformed(evt);
            }
        });

        jRadioButton127.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton127.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton127.setContentAreaFilled(false);
        jRadioButton127.setFocusPainted(false);
        jRadioButton127.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton127ActionPerformed(evt);
            }
        });

        jRadioButton128.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton128.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton128.setContentAreaFilled(false);
        jRadioButton128.setFocusPainted(false);
        jRadioButton128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton128ActionPerformed(evt);
            }
        });

        jRadioButton129.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton129.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton129.setContentAreaFilled(false);
        jRadioButton129.setFocusPainted(false);
        jRadioButton129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton129ActionPerformed(evt);
            }
        });

        jRadioButton130.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton130.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton130.setContentAreaFilled(false);
        jRadioButton130.setFocusPainted(false);
        jRadioButton130.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton130ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel74Layout = new javax.swing.GroupLayout(jPanel74);
        jPanel74.setLayout(jPanel74Layout);
        jPanel74Layout.setHorizontalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel74Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel74Layout.createSequentialGroup()
                        .addComponent(jRadioButton126)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton127)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton129)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton128)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton130)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel74Layout.setVerticalGroup(
            jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel74Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel74Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton126, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton127, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton129, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton128, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton130, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel73.add(jPanel74);
        jPanel74.setBounds(0, 160, 250, 50);

        btnModificarViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chile.png"))); // NOI18N
        btnModificarViaje.setBorderPainted(false);
        btnModificarViaje.setContentAreaFilled(false);
        btnModificarViaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarViaje.setDefaultCapable(false);
        btnModificarViaje.setFocusPainted(false);
        btnModificarViaje.setFocusable(false);
        jPanel73.add(btnModificarViaje);
        btnModificarViaje.setBounds(0, 0, 250, 160);

        jPanel71.add(jPanel73);
        jPanel73.setBounds(0, 0, 250, 200);

        jPanel75.setBackground(new java.awt.Color(156, 255, 87));
        jPanel75.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel75.setLayout(null);

        jPanel76.setBackground(new java.awt.Color(156, 255, 87));

        jLabel36.setBackground(new java.awt.Color(156, 255, 87));
        jLabel36.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Titulo del viaje");

        jLabel37.setBackground(new java.awt.Color(156, 255, 87));
        jLabel37.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Destino");

        javax.swing.GroupLayout jPanel76Layout = new javax.swing.GroupLayout(jPanel76);
        jPanel76.setLayout(jPanel76Layout);
        jPanel76Layout.setHorizontalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel76Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel76Layout.setVerticalGroup(
            jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel76Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel76Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel76Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel75.add(jPanel76);
        jPanel76.setBounds(0, 160, 250, 50);

        jPanel77.setBackground(new java.awt.Color(156, 255, 87));
        jPanel77.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel77.setLayout(null);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chile.png"))); // NOI18N
        jButton15.setBorderPainted(false);
        jButton15.setContentAreaFilled(false);
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setDefaultCapable(false);
        jButton15.setFocusPainted(false);
        jButton15.setFocusable(false);
        jPanel77.add(jButton15);
        jButton15.setBounds(0, 0, 250, 160);

        jPanel75.add(jPanel77);
        jPanel77.setBounds(0, 0, 250, 160);

        jPanel78.setBackground(new java.awt.Color(156, 255, 87));
        jPanel78.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel78.setLayout(null);

        jPanel79.setBackground(new java.awt.Color(156, 255, 87));

        jLabel40.setBackground(new java.awt.Color(156, 255, 87));
        jLabel40.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Titulo del viaje");

        jLabel59.setBackground(new java.awt.Color(156, 255, 87));
        jLabel59.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Destino");

        javax.swing.GroupLayout jPanel79Layout = new javax.swing.GroupLayout(jPanel79);
        jPanel79.setLayout(jPanel79Layout);
        jPanel79Layout.setHorizontalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel79Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel79Layout.setVerticalGroup(
            jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel79Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel79Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel79Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel78.add(jPanel79);
        jPanel79.setBounds(0, 160, 250, 50);

        jPanel80.setBackground(new java.awt.Color(156, 255, 87));
        jPanel80.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel80.setLayout(null);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chile.png"))); // NOI18N
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setDefaultCapable(false);
        jButton16.setFocusPainted(false);
        jButton16.setFocusable(false);
        jPanel80.add(jButton16);
        jButton16.setBounds(0, 0, 250, 160);

        jPanel78.add(jPanel80);
        jPanel80.setBounds(0, 0, 250, 160);

        jPanel81.setBackground(new java.awt.Color(156, 255, 87));
        jPanel81.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel81.setLayout(null);

        jPanel82.setBackground(new java.awt.Color(156, 255, 87));

        jLabel60.setBackground(new java.awt.Color(156, 255, 87));
        jLabel60.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("Titulo del viaje");

        jLabel61.setBackground(new java.awt.Color(156, 255, 87));
        jLabel61.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Destino");

        javax.swing.GroupLayout jPanel82Layout = new javax.swing.GroupLayout(jPanel82);
        jPanel82.setLayout(jPanel82Layout);
        jPanel82Layout.setHorizontalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel82Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel82Layout.setVerticalGroup(
            jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel82Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel82Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel82Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel81.add(jPanel82);
        jPanel82.setBounds(0, 160, 250, 50);

        jPanel83.setBackground(new java.awt.Color(156, 255, 87));
        jPanel83.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel83.setLayout(null);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chile.png"))); // NOI18N
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setDefaultCapable(false);
        jButton17.setFocusPainted(false);
        jButton17.setFocusable(false);
        jPanel83.add(jButton17);
        jButton17.setBounds(0, 0, 250, 160);

        jPanel81.add(jPanel83);
        jPanel83.setBounds(0, 0, 250, 160);

        jPanel84.setBackground(new java.awt.Color(156, 255, 87));
        jPanel84.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel84.setLayout(null);

        jPanel85.setBackground(new java.awt.Color(156, 255, 87));

        jLabel62.setBackground(new java.awt.Color(156, 255, 87));
        jLabel62.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("Titulo del viaje");

        jLabel63.setBackground(new java.awt.Color(156, 255, 87));
        jLabel63.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Destino");

        javax.swing.GroupLayout jPanel85Layout = new javax.swing.GroupLayout(jPanel85);
        jPanel85.setLayout(jPanel85Layout);
        jPanel85Layout.setHorizontalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel85Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel85Layout.setVerticalGroup(
            jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel85Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel85Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel85Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel84.add(jPanel85);
        jPanel85.setBounds(0, 160, 250, 50);

        jPanel86.setBackground(new java.awt.Color(156, 255, 87));
        jPanel86.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel86.setLayout(null);

        jPanel87.setBackground(new java.awt.Color(156, 255, 87));

        jLabel64.setBackground(new java.awt.Color(156, 255, 87));
        jLabel64.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel64.setText("Santiago, Chile.");

        jRadioButton131.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton131.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton131.setContentAreaFilled(false);
        jRadioButton131.setFocusPainted(false);
        jRadioButton131.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton131ActionPerformed(evt);
            }
        });

        jRadioButton132.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton132.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton132.setContentAreaFilled(false);
        jRadioButton132.setFocusPainted(false);
        jRadioButton132.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton132ActionPerformed(evt);
            }
        });

        jRadioButton133.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton133.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton133.setContentAreaFilled(false);
        jRadioButton133.setFocusPainted(false);
        jRadioButton133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton133ActionPerformed(evt);
            }
        });

        jRadioButton134.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton134.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton134.setContentAreaFilled(false);
        jRadioButton134.setFocusPainted(false);
        jRadioButton134.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton134ActionPerformed(evt);
            }
        });

        jRadioButton135.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton135.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton135.setContentAreaFilled(false);
        jRadioButton135.setFocusPainted(false);
        jRadioButton135.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton135ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel87Layout = new javax.swing.GroupLayout(jPanel87);
        jPanel87.setLayout(jPanel87Layout);
        jPanel87Layout.setHorizontalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel87Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel87Layout.createSequentialGroup()
                        .addComponent(jRadioButton131)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton132)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton134)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton133)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton135)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel87Layout.setVerticalGroup(
            jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel87Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel87Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton131, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton132, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton134, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton133, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton135, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel86.add(jPanel87);
        jPanel87.setBounds(0, 160, 250, 50);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chile.png"))); // NOI18N
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setDefaultCapable(false);
        jButton18.setFocusPainted(false);
        jButton18.setFocusable(false);
        jPanel86.add(jButton18);
        jButton18.setBounds(0, 0, 250, 160);

        jPanel84.add(jPanel86);
        jPanel86.setBounds(0, 0, 250, 200);

        jPanel88.setBackground(new java.awt.Color(156, 255, 87));
        jPanel88.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel88.setLayout(null);

        jPanel89.setBackground(new java.awt.Color(156, 255, 87));

        jLabel65.setBackground(new java.awt.Color(156, 255, 87));
        jLabel65.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Titulo del viaje");

        jLabel66.setBackground(new java.awt.Color(156, 255, 87));
        jLabel66.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel66.setText("Destino");

        javax.swing.GroupLayout jPanel89Layout = new javax.swing.GroupLayout(jPanel89);
        jPanel89.setLayout(jPanel89Layout);
        jPanel89Layout.setHorizontalGroup(
            jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel89Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel89Layout.setVerticalGroup(
            jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel89Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel89Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel89Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel88.add(jPanel89);
        jPanel89.setBounds(0, 160, 250, 50);

        jPanel90.setBackground(new java.awt.Color(156, 255, 87));
        jPanel90.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel90.setLayout(null);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chile.png"))); // NOI18N
        jButton19.setBorderPainted(false);
        jButton19.setContentAreaFilled(false);
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setDefaultCapable(false);
        jButton19.setFocusPainted(false);
        jButton19.setFocusable(false);
        jPanel90.add(jButton19);
        jButton19.setBounds(0, 0, 250, 160);

        jPanel88.add(jPanel90);
        jPanel90.setBounds(0, 0, 250, 160);

        jPanel91.setBackground(new java.awt.Color(156, 255, 87));
        jPanel91.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel91.setLayout(null);

        jPanel92.setBackground(new java.awt.Color(156, 255, 87));

        jLabel67.setBackground(new java.awt.Color(156, 255, 87));
        jLabel67.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel67.setText("Titulo del viaje");

        jLabel68.setBackground(new java.awt.Color(156, 255, 87));
        jLabel68.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel68.setText("Destino");

        javax.swing.GroupLayout jPanel92Layout = new javax.swing.GroupLayout(jPanel92);
        jPanel92.setLayout(jPanel92Layout);
        jPanel92Layout.setHorizontalGroup(
            jPanel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel92Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel92Layout.setVerticalGroup(
            jPanel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel92Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel92Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel92Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel91.add(jPanel92);
        jPanel92.setBounds(0, 160, 250, 50);

        jPanel93.setBackground(new java.awt.Color(156, 255, 87));
        jPanel93.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel93.setLayout(null);

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chile.png"))); // NOI18N
        jButton20.setBorderPainted(false);
        jButton20.setContentAreaFilled(false);
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.setDefaultCapable(false);
        jButton20.setFocusPainted(false);
        jButton20.setFocusable(false);
        jPanel93.add(jButton20);
        jButton20.setBounds(0, 0, 250, 160);

        jPanel91.add(jPanel93);
        jPanel93.setBounds(0, 0, 250, 160);

        jPanel94.setBackground(new java.awt.Color(156, 255, 87));
        jPanel94.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel94.setLayout(null);

        jPanel95.setBackground(new java.awt.Color(156, 255, 87));

        jLabel69.setBackground(new java.awt.Color(156, 255, 87));
        jLabel69.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel69.setText("Titulo del viaje");

        jLabel70.setBackground(new java.awt.Color(156, 255, 87));
        jLabel70.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText("Destino");

        javax.swing.GroupLayout jPanel95Layout = new javax.swing.GroupLayout(jPanel95);
        jPanel95.setLayout(jPanel95Layout);
        jPanel95Layout.setHorizontalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel95Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel95Layout.setVerticalGroup(
            jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel95Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel95Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel95Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel94.add(jPanel95);
        jPanel95.setBounds(0, 160, 250, 50);

        jPanel96.setBackground(new java.awt.Color(156, 255, 87));
        jPanel96.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel96.setLayout(null);

        jPanel97.setBackground(new java.awt.Color(156, 255, 87));

        jLabel71.setBackground(new java.awt.Color(156, 255, 87));
        jLabel71.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel71.setText("Santiago, Chile.");

        jRadioButton136.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton136.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton136.setContentAreaFilled(false);
        jRadioButton136.setFocusPainted(false);
        jRadioButton136.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton136ActionPerformed(evt);
            }
        });

        jRadioButton137.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton137.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton137.setContentAreaFilled(false);
        jRadioButton137.setFocusPainted(false);
        jRadioButton137.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton137ActionPerformed(evt);
            }
        });

        jRadioButton138.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton138.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton138.setContentAreaFilled(false);
        jRadioButton138.setFocusPainted(false);
        jRadioButton138.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton138ActionPerformed(evt);
            }
        });

        jRadioButton139.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton139.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton139.setContentAreaFilled(false);
        jRadioButton139.setFocusPainted(false);
        jRadioButton139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton139ActionPerformed(evt);
            }
        });

        jRadioButton140.setBackground(new java.awt.Color(156, 255, 87));
        jRadioButton140.setForeground(new java.awt.Color(56, 0, 107));
        jRadioButton140.setContentAreaFilled(false);
        jRadioButton140.setFocusPainted(false);
        jRadioButton140.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton140ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel97Layout = new javax.swing.GroupLayout(jPanel97);
        jPanel97.setLayout(jPanel97Layout);
        jPanel97Layout.setHorizontalGroup(
            jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel97Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel97Layout.createSequentialGroup()
                        .addComponent(jRadioButton136)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton137)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton139)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton138)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton140)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel97Layout.setVerticalGroup(
            jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel97Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel97Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton136, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton137, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton139, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton138, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton140, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel96.add(jPanel97);
        jPanel97.setBounds(0, 160, 250, 50);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chile.png"))); // NOI18N
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.setDefaultCapable(false);
        jButton21.setFocusPainted(false);
        jButton21.setFocusable(false);
        jPanel96.add(jButton21);
        jButton21.setBounds(0, 0, 250, 160);

        jPanel94.add(jPanel96);
        jPanel96.setBounds(0, 0, 250, 200);

        jPanel98.setBackground(new java.awt.Color(156, 255, 87));
        jPanel98.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel98.setLayout(null);

        jPanel99.setBackground(new java.awt.Color(156, 255, 87));

        jLabel72.setBackground(new java.awt.Color(156, 255, 87));
        jLabel72.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Titulo del viaje");

        jLabel73.setBackground(new java.awt.Color(156, 255, 87));
        jLabel73.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("Destino");

        javax.swing.GroupLayout jPanel99Layout = new javax.swing.GroupLayout(jPanel99);
        jPanel99.setLayout(jPanel99Layout);
        jPanel99Layout.setHorizontalGroup(
            jPanel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel99Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel99Layout.setVerticalGroup(
            jPanel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel99Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel99Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel99Layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel98.add(jPanel99);
        jPanel99.setBounds(0, 160, 250, 50);

        jPanel100.setBackground(new java.awt.Color(156, 255, 87));
        jPanel100.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel100.setLayout(null);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chile.png"))); // NOI18N
        jButton22.setBorderPainted(false);
        jButton22.setContentAreaFilled(false);
        jButton22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton22.setDefaultCapable(false);
        jButton22.setFocusPainted(false);
        jButton22.setFocusable(false);
        jPanel100.add(jButton22);
        jButton22.setBounds(0, 0, 250, 160);

        jPanel98.add(jPanel100);
        jPanel100.setBounds(0, 0, 250, 160);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel98, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel91, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jPanel75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jPanel78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel84, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jPanel88, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jPanel81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel75, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel78, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel84, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel88, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel81, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel94, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel98, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel91, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 910, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton126ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton126ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton126ActionPerformed

    private void jRadioButton127ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton127ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton127ActionPerformed

    private void jRadioButton128ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton128ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton128ActionPerformed

    private void jRadioButton129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton129ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton129ActionPerformed

    private void jRadioButton130ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton130ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton130ActionPerformed

    private void jRadioButton131ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton131ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton131ActionPerformed

    private void jRadioButton132ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton132ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton132ActionPerformed

    private void jRadioButton133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton133ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton133ActionPerformed

    private void jRadioButton134ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton134ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton134ActionPerformed

    private void jRadioButton135ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton135ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton135ActionPerformed

    private void jRadioButton136ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton136ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton136ActionPerformed

    private void jRadioButton137ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton137ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton137ActionPerformed

    private void jRadioButton138ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton138ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton138ActionPerformed

    private void jRadioButton139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton139ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton139ActionPerformed

    private void jRadioButton140ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton140ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton140ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEditarPerfil;
    public javax.swing.JButton btnModificarViaje;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel100;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JPanel jPanel84;
    private javax.swing.JPanel jPanel85;
    private javax.swing.JPanel jPanel86;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JPanel jPanel88;
    private javax.swing.JPanel jPanel89;
    private javax.swing.JPanel jPanel90;
    private javax.swing.JPanel jPanel91;
    private javax.swing.JPanel jPanel92;
    private javax.swing.JPanel jPanel93;
    private javax.swing.JPanel jPanel94;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JPanel jPanel96;
    private javax.swing.JPanel jPanel97;
    private javax.swing.JPanel jPanel98;
    private javax.swing.JPanel jPanel99;
    private javax.swing.JRadioButton jRadioButton126;
    private javax.swing.JRadioButton jRadioButton127;
    private javax.swing.JRadioButton jRadioButton128;
    private javax.swing.JRadioButton jRadioButton129;
    private javax.swing.JRadioButton jRadioButton130;
    private javax.swing.JRadioButton jRadioButton131;
    private javax.swing.JRadioButton jRadioButton132;
    private javax.swing.JRadioButton jRadioButton133;
    private javax.swing.JRadioButton jRadioButton134;
    private javax.swing.JRadioButton jRadioButton135;
    private javax.swing.JRadioButton jRadioButton136;
    private javax.swing.JRadioButton jRadioButton137;
    private javax.swing.JRadioButton jRadioButton138;
    private javax.swing.JRadioButton jRadioButton139;
    private javax.swing.JRadioButton jRadioButton140;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
