/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Holi
 */
public class vistaInicio extends javax.swing.JPanel {

    /**
     * Creates new form vistaInicioo
     */
    public vistaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInicio = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnTendencias = new javax.swing.JButton();
        btnSugerencias = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        scrollDestinos = new javax.swing.JPanel();
        scrollDestinos1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        scrollCiudad1 = new javax.swing.JScrollPane();
        pnlCiudad1 = new javax.swing.JPanel();
        scrollPlaya1 = new javax.swing.JScrollPane();
        pnlPlaya1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        scrollMontania1 = new javax.swing.JScrollPane();
        pnl_Montania1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        scrollBosque1 = new javax.swing.JScrollPane();
        pnlBosque1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        scrollSelva1 = new javax.swing.JScrollPane();
        pnlSelva1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        scrollDesierto1 = new javax.swing.JScrollPane();
        pnlDesierto1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        scrollManglar1 = new javax.swing.JScrollPane();
        pnlManglar1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        scrollVolcan1 = new javax.swing.JScrollPane();
        pnlVolcan1 = new javax.swing.JPanel();
        pnlBusqueda = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setLayout(null);

        txtBusqueda.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        txtBusqueda.setBorder(null);
        panelInicio.add(txtBusqueda);
        txtBusqueda.setBounds(90, 20, 310, 39);

        btnTendencias.setBackground(new java.awt.Color(255, 255, 255));
        btnTendencias.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        btnTendencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tendencias.png"))); // NOI18N
        btnTendencias.setText("Tendencias");
        btnTendencias.setToolTipText("");
        btnTendencias.setBorder(null);
        btnTendencias.setBorderPainted(false);
        btnTendencias.setContentAreaFilled(false);
        btnTendencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTendencias.setDefaultCapable(false);
        btnTendencias.setFocusable(false);
        btnTendencias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Line_Chart_55px.png"))); // NOI18N
        panelInicio.add(btnTendencias);
        btnTendencias.setBounds(531, 11, 121, 59);

        btnSugerencias.setBackground(new java.awt.Color(255, 255, 255));
        btnSugerencias.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        btnSugerencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sugerencias.png"))); // NOI18N
        btnSugerencias.setText("Sugerencias");
        btnSugerencias.setToolTipText("");
        btnSugerencias.setBorder(null);
        btnSugerencias.setBorderPainted(false);
        btnSugerencias.setContentAreaFilled(false);
        btnSugerencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSugerencias.setDefaultCapable(false);
        btnSugerencias.setFocusPainted(false);
        btnSugerencias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Good_Quality_55px.png"))); // NOI18N
        panelInicio.add(btnSugerencias);
        btnSugerencias.setBounds(699, 11, 126, 59);
        panelInicio.add(jSeparator2);
        jSeparator2.setBounds(90, 60, 310, 20);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        scrollDestinos.setBackground(new java.awt.Color(255, 255, 255));

        scrollDestinos1.setBackground(new java.awt.Color(255, 255, 255));
        scrollDestinos1.setPreferredSize(new java.awt.Dimension(892, 2163));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Playa");
        jLabel3.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Montaña");
        jLabel11.setToolTipText("");

        scrollCiudad1.setBackground(new java.awt.Color(255, 255, 255));
        scrollCiudad1.setBorder(null);
        scrollCiudad1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollCiudad1.setPreferredSize(new java.awt.Dimension(880, 300));

        pnlCiudad1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlCiudad1Layout = new javax.swing.GroupLayout(pnlCiudad1);
        pnlCiudad1.setLayout(pnlCiudad1Layout);
        pnlCiudad1Layout.setHorizontalGroup(
            pnlCiudad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnlCiudad1Layout.setVerticalGroup(
            pnlCiudad1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        scrollCiudad1.setViewportView(pnlCiudad1);

        scrollPlaya1.setBackground(new java.awt.Color(255, 255, 255));
        scrollPlaya1.setBorder(null);
        scrollPlaya1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollPlaya1.setPreferredSize(new java.awt.Dimension(880, 300));

        pnlPlaya1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlPlaya1Layout = new javax.swing.GroupLayout(pnlPlaya1);
        pnlPlaya1.setLayout(pnlPlaya1Layout);
        pnlPlaya1Layout.setHorizontalGroup(
            pnlPlaya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnlPlaya1Layout.setVerticalGroup(
            pnlPlaya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        scrollPlaya1.setViewportView(pnlPlaya1);

        jLabel12.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Ciudad");
        jLabel12.setToolTipText("");

        scrollMontania1.setBackground(new java.awt.Color(255, 255, 255));
        scrollMontania1.setBorder(null);
        scrollMontania1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollMontania1.setPreferredSize(new java.awt.Dimension(880, 300));

        pnl_Montania1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnl_Montania1Layout = new javax.swing.GroupLayout(pnl_Montania1);
        pnl_Montania1.setLayout(pnl_Montania1Layout);
        pnl_Montania1Layout.setHorizontalGroup(
            pnl_Montania1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
        );
        pnl_Montania1Layout.setVerticalGroup(
            pnl_Montania1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        scrollMontania1.setViewportView(pnl_Montania1);

        jLabel18.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Bosque");
        jLabel18.setToolTipText("");

        scrollBosque1.setBackground(new java.awt.Color(255, 255, 255));
        scrollBosque1.setBorder(null);
        scrollBosque1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollBosque1.setPreferredSize(new java.awt.Dimension(880, 300));

        pnlBosque1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlBosque1Layout = new javax.swing.GroupLayout(pnlBosque1);
        pnlBosque1.setLayout(pnlBosque1Layout);
        pnlBosque1Layout.setHorizontalGroup(
            pnlBosque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnlBosque1Layout.setVerticalGroup(
            pnlBosque1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        scrollBosque1.setViewportView(pnlBosque1);

        jLabel19.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Selva");
        jLabel19.setToolTipText("");

        scrollSelva1.setBackground(new java.awt.Color(255, 255, 255));
        scrollSelva1.setBorder(null);
        scrollSelva1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollSelva1.setPreferredSize(new java.awt.Dimension(880, 300));

        pnlSelva1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlSelva1Layout = new javax.swing.GroupLayout(pnlSelva1);
        pnlSelva1.setLayout(pnlSelva1Layout);
        pnlSelva1Layout.setHorizontalGroup(
            pnlSelva1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1386, Short.MAX_VALUE)
        );
        pnlSelva1Layout.setVerticalGroup(
            pnlSelva1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        scrollSelva1.setViewportView(pnlSelva1);

        jLabel20.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Desierto");
        jLabel20.setToolTipText("");

        scrollDesierto1.setBackground(new java.awt.Color(255, 255, 255));
        scrollDesierto1.setBorder(null);
        scrollDesierto1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollDesierto1.setPreferredSize(new java.awt.Dimension(880, 300));

        pnlDesierto1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlDesierto1Layout = new javax.swing.GroupLayout(pnlDesierto1);
        pnlDesierto1.setLayout(pnlDesierto1Layout);
        pnlDesierto1Layout.setHorizontalGroup(
            pnlDesierto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnlDesierto1Layout.setVerticalGroup(
            pnlDesierto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        scrollDesierto1.setViewportView(pnlDesierto1);

        jLabel21.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Zona Volcánica");
        jLabel21.setToolTipText("");

        scrollManglar1.setBackground(new java.awt.Color(255, 255, 255));
        scrollManglar1.setBorder(null);
        scrollManglar1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollManglar1.setPreferredSize(new java.awt.Dimension(880, 300));

        pnlManglar1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlManglar1Layout = new javax.swing.GroupLayout(pnlManglar1);
        pnlManglar1.setLayout(pnlManglar1Layout);
        pnlManglar1Layout.setHorizontalGroup(
            pnlManglar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnlManglar1Layout.setVerticalGroup(
            pnlManglar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        scrollManglar1.setViewportView(pnlManglar1);

        jLabel22.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Manglar");
        jLabel22.setToolTipText("");

        scrollVolcan1.setBackground(new java.awt.Color(255, 255, 255));
        scrollVolcan1.setBorder(null);
        scrollVolcan1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollVolcan1.setPreferredSize(new java.awt.Dimension(880, 300));

        pnlVolcan1.setBackground(new java.awt.Color(255, 255, 255));
        pnlVolcan1.setMaximumSize(new java.awt.Dimension(1366, 300));

        javax.swing.GroupLayout pnlVolcan1Layout = new javax.swing.GroupLayout(pnlVolcan1);
        pnlVolcan1.setLayout(pnlVolcan1Layout);
        pnlVolcan1Layout.setHorizontalGroup(
            pnlVolcan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        pnlVolcan1Layout.setVerticalGroup(
            pnlVolcan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        scrollVolcan1.setViewportView(pnlVolcan1);

        javax.swing.GroupLayout scrollDestinos1Layout = new javax.swing.GroupLayout(scrollDestinos1);
        scrollDestinos1.setLayout(scrollDestinos1Layout);
        scrollDestinos1Layout.setHorizontalGroup(
            scrollDestinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                .addGroup(scrollDestinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scrollDestinos1Layout.createSequentialGroup()
                        .addGroup(scrollDestinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(scrollDestinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(scrollMontania1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(scrollPlaya1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(scrollCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(scrollBosque1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(scrollSelva1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(scrollDesierto1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(scrollManglar1, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, scrollDestinos1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollVolcan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        scrollDestinos1Layout.setVerticalGroup(
            scrollDestinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scrollDestinos1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(scrollDestinos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(scrollDestinos1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(scrollMontania1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(scrollPlaya1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(scrollCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(scrollBosque1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(scrollSelva1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(scrollDesierto1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel22)
                .addGap(8, 8, 8)
                .addComponent(scrollManglar1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollVolcan1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        pnlBusqueda.setPreferredSize(new java.awt.Dimension(892, 2163));

        javax.swing.GroupLayout pnlBusquedaLayout = new javax.swing.GroupLayout(pnlBusqueda);
        pnlBusqueda.setLayout(pnlBusquedaLayout);
        pnlBusquedaLayout.setHorizontalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        pnlBusquedaLayout.setVerticalGroup(
            pnlBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout scrollDestinosLayout = new javax.swing.GroupLayout(scrollDestinos);
        scrollDestinos.setLayout(scrollDestinosLayout);
        scrollDestinosLayout.setHorizontalGroup(
            scrollDestinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(scrollDestinos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        scrollDestinosLayout.setVerticalGroup(
            scrollDestinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 2479, Short.MAX_VALUE)
            .addComponent(scrollDestinos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlBusqueda.getAccessibleContext().setAccessibleParent(scrollDestinos);

        jScrollPane2.setViewportView(scrollDestinos);

        panelInicio.add(jScrollPane2);
        jScrollPane2.setBounds(0, 80, 910, 490);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        panelInicio.add(jLabel2);
        jLabel2.setBounds(20, 10, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSugerencias;
    public javax.swing.JButton btnTendencias;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JLabel jLabel22;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelInicio;
    public javax.swing.JPanel pnlBosque1;
    public javax.swing.JPanel pnlBusqueda;
    public javax.swing.JPanel pnlCiudad1;
    public javax.swing.JPanel pnlDesierto1;
    public javax.swing.JPanel pnlManglar1;
    public javax.swing.JPanel pnlPlaya1;
    public javax.swing.JPanel pnlSelva1;
    public javax.swing.JPanel pnlVolcan1;
    public javax.swing.JPanel pnl_Montania1;
    public javax.swing.JScrollPane scrollBosque1;
    public javax.swing.JScrollPane scrollCiudad1;
    public javax.swing.JScrollPane scrollDesierto1;
    public javax.swing.JPanel scrollDestinos;
    public javax.swing.JPanel scrollDestinos1;
    public javax.swing.JScrollPane scrollManglar1;
    public javax.swing.JScrollPane scrollMontania1;
    public javax.swing.JScrollPane scrollPlaya1;
    public javax.swing.JScrollPane scrollSelva1;
    public javax.swing.JScrollPane scrollVolcan1;
    public javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
